### ISSUE TITLE
Cant fetch scripts from sub folder of the scriptPath

### ISSUE THREAD

**Issue by shaynechmad** [patka/cassandra-migration#16]
I set script location to = "db/migration/cassandra" and inside this folder i have another folder named "init" (I want to separate the scripts to sub folders for each version).

When i run the migration i get exception: 
`Exception in thread "main" org.cognitor.cassandra.migration.MigrationException: Error for script init/100000000_dbCreation.cql. Unable to extract version.
	at org.cognitor.cassandra.migration.MigrationRepository.extractScriptVersion(MigrationRepository.java:203)
	at org.cognitor.cassandra.migration.MigrationRepository.scanForScripts(MigrationRepository.java:185)
	at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:132)
	at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:114)
	at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:102)
	at com.solaredge.dbc.cassndra.migration.CassandraMigrator.migrate(CassandraMigrator.java:74)
	at com.solaredge.dbc.cassndra.migration.CassandraMigrator.main(CassandraMigrator.java:64)
Caused by: java.lang.NumberFormatException: For input string: "init/100000000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.cognitor.cassandra.migration.MigrationRepository.extractScriptVersion(MigrationRepository.java:201)
	... 6 more`

After a quick debugging, the function 'extractScriptName' return the scriptName only without the script location that i set in the beginning (db/migration/cassandra) and return the sub folder with the script name (it returned 'init/100000000_dbCreation.cql' instead of '100000000_dbCreation.cql').

I changed the function extractScriptName to :
`private String extractScriptName(String resourceName) {
        return resourceName.substring(resourceName.lastIndexOf("/"));
}`
 and its work fine.

**Comment by patka** [comment]
Hello,
thanks for finding and reporting this issue. I committed a fix for this yesterday afternoon. Could you please verify that it works for you?
Cheers
Patrick

**Comment by shaynechmad** [comment]
Hi,
it works fine :)
many thanks for the quick response.

Shay

**Comment by patka** [comment]
Hi,
you're welcome. When it is small things like this I can fix them quite fast, for your other bug I guess it will take me a while longer to solve it.... unfortunately.
Cheers
Patrick
