### ISSUE TITLE
Looks for cassandra/migration folder as if it is in a ZIP path

### ISSUE THREAD

**Issue by Ebeid** [patka/cassandra-migration#26]
Hello,

We are using version 2.1.2:

compile('org.cognitor.cassandra:cassandra-migration-spring-boot-starter:2.1.2')

Until last Friday migrator used to work and pickup cql files from cassandra/migration folder. This week it started treat cassandra/migration as if it exist in a zipped folder. Notice classes**!**/cassandra/migration/

PS: We are using the default migration folder

MigrationTask migration = new MigrationTask(database, new MigrationRepository());
migration.migrate();

below is the exception that we getting from the application:

17:38:10.783 [main] DEBUG org.cognitor.cassandra.migration.MigrationRepository - Scanning for cql migration scripts in cassandra/migration/
17:38:10.784 [main] DEBUG org.cognitor.cassandra.migration.MigrationRepository - Potential script folder: jar:file:/Users/myuser/Documents/sourcecode/myservice/build/libs/myservice-1.0.jar!/BOOT-INF/classes!/cassandra/migration/
17:38:10.784 [main] DEBUG org.cognitor.cassandra.migration.scanner.JarLocationScanner - Scanning in jar jar:file:/Users/myuser/Documents/sourcecode/myservice/build/libs/myservice-1.0.jar!/BOOT-INF/classes!/cassandra/migration/ in location cassandra/migration/
17:38:10.784 [main] DEBUG org.cognitor.cassandra.migration.scanner.JarLocationScanner - Trying to get existing filesystem for jar:file:/Users/myuser/Documents/sourcecode/myservice/build/libs/myservice-1.0.jar!/BOOT-INF/classes!/cassandra/migration/
17:38:10.789 [main] DEBUG org.cognitor.cassandra.migration.scanner.JarLocationScanner - Creating new filesystem for jar:file:/Users/myuser/Documents/sourcecode/myservice/build/libs/myservice-1.0.jar!/BOOT-INF/classes!/cassandra/migration/
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.cognitor.cassandra.migration.MigrationException: Error while scanning script folder for new scripts.
	at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:133)
	at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:114)
	at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:102)
	at com.philips.ri.myservice.myserviceApplication.main(myserviceApplication.java:33)
	... 8 more
Caused by: java.nio.file.NoSuchFileException: cassandra/migration
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.getAttributes(ZipPath.java:729)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1755)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3653)
	at java.base/java.nio.file.Files.walk(Files.java:3707)
	at org.cognitor.cassandra.migration.scanner.JarLocationScanner.findResourceNames(JarLocationScanner.java:34)
	at org.cognitor.cassandra.migration.MigrationRepository.scanForScripts(MigrationRepository.java:181)
	at org.cognitor.cassandra.migration.MigrationRepository.<init>(MigrationRepository.java:131)
	... 11 more

**Comment by patka** [comment]
Hi Ebeid,

did you do some changes to your Spring applications configuration lately? Usually, when you use the spring boot starter library, it should replace the default JarLocationScanner with the SpringBootLocationScanner that knows how to handle the some specialties that are introduced by Spring. According to you log output, your application is still using the JarLocationScanner. To me it seems that the Spring auto configuration is not executed. Can you verify this?

Do you have this problem only when you start the standalone jar or also when you run the application inside your IDE.

Cheers
Patrick

**Comment by patka** [comment]
Hi Ebeid,

normally you should be able to exclude the CassandraMigrationAutoConfiguration in your configuration code like this:

`@EnableAutoConfiguration(exclude = CassandraMigrationAutoConfiguration.class)`

This would allow you to use the SpringBootLocationScanner from the dependency without making a copy into your codebase which is in general not a good practice as you will be excluded from every update that will happen to it.

Does the Spring auto configuration not work for you? As far as I can tell you are not doing anything special except for the IgnoreDuplicatesCollector. 

Cheers
Patrick

**Comment by ChandraDuddukuri** [comment]
Hallo Patrick,
While using version 2.2.0 on windows, with both the Jars included, my Spring boot Maven application is working fine. But when is used it on Linux, i am facing the issue as mentioned by **Ebeid**.

I tried the solution mentioned by **Ebeid** with version 2.1.2 (Scanner locally and only one Jar included) and it's working on both Windows & Linux environments.

Regards,
Chandra
